version: '3.3'

services:
  balance-aggregator-postgres:
    # Use this postgres image https://github.com/Giveth/postgres-givethio
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_DB=balance-aggregator
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5532:5532"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - balance-aggregator
    command: -p 5532
volumes:
  db-data:

networks:
  balance-aggregator:
